/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MarkSter {
        "searchWords": string;
        "text": string;
    }
}
declare global {
    interface HTMLMarkSterElement extends Components.MarkSter, HTMLStencilElement {
    }
    var HTMLMarkSterElement: {
        prototype: HTMLMarkSterElement;
        new (): HTMLMarkSterElement;
    };
    interface HTMLElementTagNameMap {
        "mark-ster": HTMLMarkSterElement;
    }
}
declare namespace LocalJSX {
    interface MarkSter {
        "searchWords"?: string;
        "text"?: string;
    }
    interface IntrinsicElements {
        "mark-ster": MarkSter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mark-ster": LocalJSX.MarkSter & JSXBase.HTMLAttributes<HTMLMarkSterElement>;
        }
    }
}
